# Generated by Django 3.1.7 on 2021-08-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokem', '0003_auto_20210804_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemondata',
            name='move',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
