# Generated by Django 3.1.7 on 2021-08-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokem', '0005_pokemondata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemondata',
            name='abilities',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
