# Generated by Django 3.1.7 on 2021-08-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokem', '0006_pokemondata_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemondata',
            name='move',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
