# Generated by Django 3.1.7 on 2021-08-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokem', '0007_auto_20210804_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemondata',
            name='main_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
