# Generated by Django 3.1.7 on 2021-08-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokem', '0010_pokemondata_u_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemondata',
            name='u_name',
        ),
    ]
