# Generated by Django 3.1.7 on 2021-08-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokem', '0011_remove_pokemondata_u_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemondata',
            name='u_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
